/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StylesIndexRouteImport } from './routes/styles.index'
import { Route as StylesIdRouteImport } from './routes/styles.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesIndexRoute = StylesIndexRouteImport.update({
  id: '/styles/',
  path: '/styles/',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesIdRoute = StylesIdRouteImport.update({
  id: '/styles/$id',
  path: '/styles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/styles/$id': typeof StylesIdRoute
  '/styles/': typeof StylesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/styles/$id': typeof StylesIdRoute
  '/styles': typeof StylesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/styles/$id': typeof StylesIdRoute
  '/styles/': typeof StylesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/styles/$id' | '/styles/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/styles/$id' | '/styles'
  id: '__root__' | '/' | '/settings' | '/styles/$id' | '/styles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  StylesIdRoute: typeof StylesIdRoute
  StylesIndexRoute: typeof StylesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/': {
      id: '/styles/'
      path: '/styles'
      fullPath: '/styles/'
      preLoaderRoute: typeof StylesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/$id': {
      id: '/styles/$id'
      path: '/styles/$id'
      fullPath: '/styles/$id'
      preLoaderRoute: typeof StylesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  StylesIdRoute: StylesIdRoute,
  StylesIndexRoute: StylesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
